const funFacts = [
    "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
    "Bananas are berries, but strawberries are not.",
    "The world's largest pizza was 1261.65 square meters (13,580.28 square feet) and was made in Italy.",
    "Carrots were originally purple.",
    "The world's most expensive coffee is made using civet poop; it's called Kopi Luwak.",
    "The hottest chili pepper in the world is the Carolina Reaper.",
    "Peanuts are not nuts; they are legumes.",
    "Apples float in water because they are 25% air.",
    "The fear of cooking is called Mageirocophobia.",
    "The world's oldest known recipe is for beer.",
    "Ketchup was used as a medicine in the 1800s.",
    "The average American eats about 18 acres of pizza in their lifetime.",
    "Lemons contain more sugar than strawberries.",
    "Honey is the only natural food that never spoils.",
    "The fear of vegetables is called Lachanophobia.",
    "Almonds are a member of the peach family.",
    "Cucumbers are a fruit, not a vegetable.",
    "Honeydew and cantaloupe are both members of the gourd family.",
    "The word 'avocado' comes from the Aztec word for testicle.",
    "The first recorded recipe for ice cream was in the 17th century.",
    "Nutmeg is extremely poisonous if injected intravenously.",
    "Cashews come from a fruit.",
    "Oranges are a type of berry.",
    "Popsicles were invented by an 11-year-old in 1905.",
    "A pineapple is a collection of berries fused together.",
    "The world's most massive jaffa cake weighed over 1220 kilograms.",
    "Worcestershire sauce is made from anchovies.",
    "The world's most extensive chocolate bar weighed over 5,000 pounds.",
    "A single spaghetti noodle is called a 'spaghetto.'",
    "Chocolate was once used as currency by the Aztecs.",
    "McDonald's once made bubblegum-flavored broccoli to encourage kids to eat more vegetables.",
    "The world's most expensive spice is saffron.",
    "The world's largest cabbage weighed more than 138 pounds.",
    "Celery has negative calories; it takes more energy to eat and digest than it provides.",
    "The fear of running out of food is called 'Cibophobia.'",
    "In Japan, KFC is a traditional Christmas meal.",
    "The world's largest omelette weighed over 6 tons.",
    "The oldest known recipe is a recipe for beer in a Sumerian poem dating back to around 3500 BCE.",
    "Honey is the only food that does not spoil.",
    "Pineapples take almost three years to grow.",
    "The most expensive pizza in the world costs over $12,000 and is topped with caviar and gold leaf.",
    "The word 'soup' comes from the Sanskrit word 'sop,' which means to drink.",
    "The world's most massive lasagna weighed over 5 tons.",
    "The first recorded use of the word 'sandwich' was in 1762.",
    "Cinnamon comes from the bark of a tree.",
    "There are more than 7,500 varieties of apples worldwide.",
    "The world's largest chocolate bar weighed over 12,770 pounds.",
    "The fear of peanut butter sticking to the roof of your mouth is called Arachibutyrophobia.",
    "Honeybees must tap two million flowers to make one pound of honey.",
    "The average person will eat around 35 tons of food in their lifetime."
  ];
  
  export default funFacts;